/// Tool that executes code generated by the model, and automatically returns the result to the model.
///
/// See also ``ExecutableCode`` and ``CodeExecutionResult`` which are only generated when using this tool.
///
/// <https://ai.google.dev/api/caching#CodeExecution>
public struct CodeExecution: Codable, Sendable {
    // This type has no fields.
    
    public init() {
    }
}
