/// Code generated by the model that is meant to be executed, and the result returned to the model.
///
/// Only generated when using the ``CodeExecution`` tool, in which the code will be automatically executed, and a corresponding ``CodeExecutionResult`` will also be generated.
///
/// <https://ai.google.dev/api/caching#ExecutableCode>
public struct ExecutableCode: Codable, Sendable {
    // this declaration is not complete - see documentation above for all fields
}
