/// Incremental server update generated by the model in response to client messages.
///
/// Content is generated as quickly as possible, and not in real time. Clients may choose to buffer and play it out in real time.
///
/// <https://ai.google.dev/api/live#bidigeneratecontentservercontent>
public struct BidiGenerateContentServerContent: Codable, Sendable {
    /// Output only. If true, indicates that the model is done generating.
    ///
    /// When model is interrupted while generating there will be no 'generation_complete' message in interrupted turn, it will go through 'interrupted > turn_complete'.
    ///
    /// When model assumes realtime playback there will be delay between generation_complete and turn_complete that is caused by model waiting for playback to finish.
    public let generationComplete: Bool?
    /// Output only. If true, indicates that the model has completed its turn.
    /// Generation will only start in response to additional client messages.
    public let turnComplete: Bool?
    /// Output only. If true, indicates that a client message has interrupted current model generation.
    /// If the client is playing out the content in real time, this is a good signal to stop and empty the current playback queue.
    public let interrupted: Bool?
    /// Output only. Grounding metadata for the generated content.
    public let groundingMetadata: GroundingMetadata?
    /// Output only. Input audio transcription. The transcription is sent independently of the other server messages and there is no guaranteed ordering.
    public let inputTranscription: BidiGenerateContentTranscription?
    /// Output only. Output audio transcription.
    ///
    /// The transcription is sent independently of the other server messages and there is no guaranteed ordering, in particular not between serverContent and this outputTranscription.
    public let outputTranscription: BidiGenerateContentTranscription?
    // (no doc comment)
    public let urlContextMetadata: UrlContextMetadata?
    /// Output only. The content that the model has generated as part of the current conversation with the user.
    public let modelTurn: Content?
    
    public init(
        generationComplete: Bool?, turnComplete: Bool?,
        interrupted: Bool?,
        groundingMetadata: GroundingMetadata?,
        inputTranscription: BidiGenerateContentTranscription?,
        outputTranscription: BidiGenerateContentTranscription?,
        urlContextMetadata: UrlContextMetadata?,
        modelTurn: Content?
    ) {
        self.generationComplete = generationComplete
        self.turnComplete = turnComplete
        self.interrupted = interrupted
        self.groundingMetadata = groundingMetadata
        self.inputTranscription = inputTranscription
        self.outputTranscription = outputTranscription
        self.urlContextMetadata = urlContextMetadata
        self.modelTurn = modelTurn
    }
}
