/// Response message for the BidiGenerateMusic call.
///
/// <https://ai.google.dev/api/live_music#bidigeneratemusicservermessage>
public struct BidiGenerateMusicServerMessage: Sendable {
    public enum Payload: Sendable {
        /// Output only. Sent in response to a ``BidiGenerateMusicSetup`` message from the client when setup is complete.
        case setupComplete(BidiGenerateMusicSetupComplete)
        /// Output only. Content generated by the model in response to client messages.
        case serverContent(BidiGenerateMusicServerContent)
        /// Output only. Filtered prompt with reason.
        case filteredPrompt(BidiGenerateMusicFilteredPrompt)
        /// Output only. The warning message from the server. Warnings won't terminate the stream.
        case warning(String)
    }
    
    /// The type of the message.
    public let messageType: Payload
}

extension BidiGenerateMusicServerMessage: Codable {
    enum CodingKeys: String, CodingKey {
        // messageType
        case setupComplete
        case serverContent
        case filteredPrompt
        case warning
    }
    
    public init(from decoder: any Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        
        if let value = try container.decodeIfPresent(BidiGenerateMusicSetupComplete.self, forKey: .setupComplete) {
            self.messageType = .setupComplete(value)
        } else if let value = try container.decodeIfPresent(BidiGenerateMusicServerContent.self, forKey: .serverContent) {
            self.messageType = .serverContent(value)
        } else if let value = try container.decodeIfPresent(BidiGenerateMusicFilteredPrompt.self, forKey: .filteredPrompt) {
            self.messageType = .filteredPrompt(value)
        } else if let value = try container.decodeIfPresent(String.self, forKey: .warning) {
            self.messageType = .warning(value)
        } else {
            let allKeys: [CodingKeys] = [.setupComplete, .serverContent, .filteredPrompt, .warning]
            let keysFormatted = allKeys
                .map { "'\($0.rawValue)'" }
                .joined(separator: ", ")
            throw DecodingError.dataCorrupted(.init(codingPath: decoder.codingPath, debugDescription: "Expected one of \(keysFormatted)"))
        }
    }
    
    public func encode(to encoder: any Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        
        switch messageType {
        case .setupComplete(let value):
            try container.encode(value, forKey: .setupComplete)
        case .serverContent(let value):
            try container.encode(value, forKey: .serverContent)
        case .filteredPrompt(let value):
            try container.encode(value, forKey: .filteredPrompt)
        case .warning(let value):
            try container.encode(value, forKey: .warning)
        }
    }
}
