/// Incremental server update generated by the model in response to client messages.
///
/// Content is generated as quickly as possible, and not in real time.
/// Clients may choose to buffer and play it out in real time.
///
/// <https://ai.google.dev/api/live_music#bidigeneratemusicservercontent>
public struct BidiGenerateMusicServerContent: Codable, Sendable {
    // this declaration is not complete - see documentation above for all fields
}
