name: Build documentation

on: push

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install workflow dependencies
        run: |
          ( brew list xcbeautify &> /dev/null ) || brew install xcbeautify

      - name: Build
        run: |
          # https://github.com/cpisciotta/xcbeautify#github-actions

          set -o pipefail && xcodebuild docbuild \
            -scheme 'Gemini-Package' \
            -config Release \
            -destination 'generic/platform=macOS' | xcbeautify --renderer github-actions
